version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.8-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
